# Generated by Django 4.2.7 on 2023-12-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_tarefas_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='email',
            field=models.EmailField(default='teste@teste.com', max_length=254),
        ),
    ]
