# Generated by Django 4.2.7 on 2023-12-03 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0004_alter_tarefas_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='email',
        ),
    ]
