# Generated by Django 4.2.7 on 2023-12-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0009_alter_tarefas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='email',
            field=models.EmailField(default='teste@teste.com', max_length=255),
        ),
    ]
