# Generated by Django 4.2.7 on 2023-12-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0010_alter_tarefas_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
